name: proxy_core
description: "Proxy Core plugin for Flutter apps providing xray, singbox and ... implementation"
version: 6.9.6
homepage: none

environment:
  sdk: ^3.5.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  grpc: ^4.1.0
  protobuf: ^4.2.0
  ffi: ^2.1.4
  flutter_local_notifications: ^19.4.2
  permission_handler: ^12.0.1
  fixnum: ^1.1.1

dev_dependencies:
  ffigen: ^19.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mahsanet.proxy_core
        pluginClass: ProxyCorePlugin
        ffiPlugin: true
      ios:
        pluginClass: ProxyCorePlugin
  
      windows:
        ffiPlugin: true
      macos:
        ffiPlugin: true